
CREATE TABLE IF NOT EXISTS Item(
	ItemID INTEGER NOT NULL,
	Name VARCHAR(500) NOT NULL, 
	Seller VARCHAR(200)  NOT NULL, 
	Currently DECIMAL(8,2) NOT NULL, 
	Buy_Price DECIMAL(8,2) NULL, 
	First_Bid DECIMAL(8,2) NOT NULL, 
	location VARCHAR(500) NOT NULL, 
	Latitude INTEGER NULL, 
	Longitude INTEGER NULL, 
	Country VARCHAR(40) NOT NULL, 
	Started TIMESTAMP NOT NULL, 
	Ends TIMESTAMP NOT NULL, 
	Description VARCHAR(4000) NOT NULL,
	PRIMARY KEY (ItemID));


CREATE TABLE IF NOT EXISTS Seller(
	UserID VARCHAR(200) NOT NULL,
	Rating INTEGER NOT NULL,
	PRIMARY KEY (UserID));


CREATE TABLE IF NOT EXISTS Bidder(
	UserID VARCHAR(200) NOT NULL, 
	Rating INTEGER NOT NULL,
	Location VARCHAR(500) NULL, 
	Country VARCHAR(200) NULL,
	PRIMARY KEY (UserID));

CREATE TABLE IF NOT EXISTS BidInfo(
	ItemID INTEGER NOT NULL,
	BidderID VARCHAR(200) NOT NULL,
	Time TIMESTAMP NOT NULL, 
	Amount INTEGER NOT NULL,
	PRIMARY KEY (ItemID, BidderID, Time));


CREATE TABLE IF NOT EXISTS Category(
	ItemID INTEGER NOT NULL,
	Category VARCHAR(200),
	PRIMARY KEY(ItemID, Category));

