
LOAD DATA LOCAL INFILE 'item_uniq.dat' INTO TABLE Item
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'seller_uniq.dat' INTO TABLE Seller
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'bidder_uniq.dat' INTO TABLE Bidder
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'bidInfo_uniq.dat' INTO TABLE BidInfo
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'category_uniq.dat' INTO TABLE Category
FIELDS TERMINATED BY '|*|';
/*SHOW TABLES;*/
/*DESCRIBE Seller;*/